[unittest] Fix missing user-provided default constructor
error: default initialization of an object of const type 'const Pod'
without a user-provided default constructor

git-svn-id: https://llvm.org/svn/llvm-project/lldb/trunk@354602 91177308-0d34-0410-b5e6-96231b3b80d8