Revert r205769 as it breaks the build on FreeBSD:
error: declaration of constexpr static data member 'spec' requires an
initializer


git-svn-id: https://llvm.org/svn/llvm-project/lldb/trunk@205776 91177308-0d34-0410-b5e6-96231b3b80d8