[lldb] [Plugins/SysV-x86_64] NetBSD is also using SysV ABI
Reenable SysV x86_64 ABI usage on NetBSD that was accidentally removed
in r364216.  This fixes numerous test failures with messages similar
to the following:

  error: Can't run the expression locally: Interpreter doesn't handle
  one of the expression's opcodes

git-svn-id: https://llvm.org/svn/llvm-project/lldb/trunk@364503 91177308-0d34-0410-b5e6-96231b3b80d8